server:
  port: 8282
  servlet:
    context-path: /asuntech
logging.level.org.springframework.boot.autoconfigure: ERROR
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: 10000ms
        min-idle: 20
uploadFile:
  path: C:\\FileUpload\\
---
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/distribution?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    sql:
      url: jdbc:sqlserver://127.0.0.1;databaseName =db1
      username: sa
      password: 123456
    oracle:
      url: jdbc:oracle:thin:@118.24.153.227:1521:TEST
      username: TEST
      password: 134167
      driverClassName: oracle.jdbc.driver.OracleDriver
    h2:
      username: root
      password: 123456
      url: jdbc:h2:file:~/.h2/h2
    spring:
      profiles:
        active: dev
