server:
  port: 8080
  servlet:
    context-path: /asuntech
logging.level.org.springframework.boot.autoconfigure: ERROR
spring:
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    sql:
      url: jdbc:sqlserver://127.0.0.1;databaseName =db1
      username: sa
      password: 123456